/**
 * 表情库扩展： QQ 表情
 */
// https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/0.gif
const icons = [
  { name: "微笑", img: "0.gif" },
  { name: "撇嘴", img: "1.gif" },
  { name: "色", img: "2.gif" },
  { name: "发呆", img: "3.gif" },
  { name: "得意", img: "4.gif" },
  { name: "流泪", img: "5.gif" },
  { name: "害羞", img: "6.gif" },
  { name: "闭嘴", img: "7.gif" },
  { name: "睡", img: "8.gif" },
  { name: "大哭", img: "9.gif" },
  { name: "尴尬", img: "10.gif" },
  { name: "发怒", img: "11.gif" },
  { name: "调皮", img: "12.gif" },
  { name: "呲牙", img: "13.gif" },
  { name: "惊讶", img: "14.gif" },
  { name: "难过", img: "15.gif" },
  { name: "酷", img: "16.gif" },
  { name: "囧", img: "17.gif" },
  { name: "抓狂", img: "18.gif" },
  { name: "吐", img: "19.gif" },
  { name: "偷笑", img: "20.gif" },
  { name: "愉快", img: "21.gif" },
  { name: "白眼", img: "22.gif" },
  { name: "傲慢", img: "23.gif" },
  { name: "饿", img: "24.gif" },
  { name: "困", img: "25.gif" },
  { name: "惊恐", img: "26.gif" },
  { name: "流汗", img: "27.gif" },
  { name: "憨笑", img: "28.gif" },
  { name: "悠闲", img: "29.gif" },
  { name: "努力", img: "30.gif" },
  { name: "咒骂", img: "31.gif" },
  { name: "疑问", img: "32.gif" },
  { name: "嘘", img: "33.gif" },
  { name: "晕", img: "34.gif" },
  { name: "抓狂", img: "35.gif" },
  { name: "衰", img: "36.gif" },
  { name: "骷髅", img: "37.gif" },
  { name: "敲打", img: "38.gif" },
  { name: "再见", img: "39.gif" },
  { name: "擦汗", img: "40.gif" },
  { name: "抠鼻", img: "41.gif" },
  { name: "鼓掌", img: "42.gif" },
  { name: "糗大了", img: "43.gif" },
  { name: "坏笑", img: "44.gif" },
  { name: "左哼哼", img: "45.gif" },
  { name: "右哼哼", img: "46.gif" },
  { name: "打哈欠", img: "47.gif" },
  { name: "鄙视", img: "48.gif" },
  { name: "委屈", img: "49.gif" },
  { name: "快哭了", img: "50.gif" },
  { name: "奸笑", img: "51.gif" },
  { name: "亲亲", img: "52.gif" },
  { name: "吓", img: "53.gif" },
  { name: "可怜", img: "54.gif" },
  { name: "赞", img: "79.gif" },
  { name: "踩", img: "80.gif" },
  { name: "握手", img: "81.gif" },
  { name: "胜利", img: "82.gif" },
  { name: "抱拳", img: "83.gif" },
  { name: "勾引", img: "84.gif" },
  { name: "拳头", img: "85.gif" },
  { name: "差劲", img: "86.gif" },
  { name: "爱你", img: "87.gif" },
  { name: " NO ", img: "88.gif" },
  { name: " OK ", img: "89.gif" },
  { name: "菜刀", img: "55.gif" },
  { name: "西瓜", img: "56.gif" },
  { name: "啤酒", img: "57.gif" },
  { name: "篮球", img: "58.gif" },
  { name: "乒乓球", img: "59.gif" },
  { name: "咖啡", img: "60.gif" },
  { name: "吃饭", img: "61.gif" },
  { name: "猪头", img: "62.gif" },
  { name: "玫瑰", img: "63.gif" },
  { name: "凋谢", img: "64.gif" },
  { name: "嘴唇", img: "65.gif" },
  { name: "爱心", img: "66.gif" },
  { name: "心碎", img: "67.gif" },
  { name: "蛋糕", img: "68.gif" },
  { name: "闪电", img: "69.gif" },
  { name: "炸弹", img: "70.gif" },
  { name: "刀", img: "71.gif" },
  { name: "足球", img: "72.gif" },
  { name: "瓢虫", img: "73.gif" },
  { name: "便便", img: "74.gif" },
  { name: "月亮", img: "75.gif" },
  { name: "太阳", img: "76.gif" },
  { name: "礼物", img: "77.gif" },
  { name: "拥抱", img: "78.gif" }
]

const emoticons = {};
for (let i = 0; i < icons.length; i++) {
  let icon = icons[i]
  emoticons[icon.name] = {
    keywords: [icon.name],
    char: '<img data-emoticon="true" style="width:1.3em;height:1.3em;margin:0;vertical-align:-.25em" draggable="false" alt="' + icon.name + '" src="../qqemoji/' + icon.img + '"/>',
    fitzpatrick_scale: false,
    category: icon.category || 'QQ'
  }
}

export default emoticons
